# Generated by Django 3.2.16 on 2022-12-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nom de la librairie')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('city', models.CharField(max_length=255, verbose_name='Ville')),
                ('postal_code', models.CharField(max_length=255, verbose_name='Code postal')),
                ('statut', models.CharField(default='Actif', max_length=255, verbose_name='Statut de la librairie')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Librairie',
                'verbose_name_plural': 'Librairies',
                'ordering': ['-created_at'],
            },
        ),
    ]
