# Generated by Django 3.2.16 on 2023-01-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0003_auto_20230101_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description de la librairie'),
        ),
    ]
